// /billing (MASTER_SPEC §4 + Amendment A): the offer ladder + a live contract preview. Server
// component — reads config/pricing.yaml through @autopilot/billing (single source of truth) and
// renders a real generated contract, so the "mispricing is impossible" guarantee is demonstrated, not
// asserted. force-static: the config reads happen at build, nothing hits the filesystem at runtime.
import { Card, PageHeader, SectionTitle } from "@/components/ui";
import { type Product, generateContract, isRangeProduct, loadPricing } from "@autopilot/billing";

export const dynamic = "force-static";

function money(n: number): string {
  return `$${n.toLocaleString("en-US")}`;
}

function priceLine(p: Product): { setup: string; monthly: string } {
  if (isRangeProduct(p)) {
    return {
      setup: `${money(p.setup_min)}–${money(p.setup_max)}`,
      monthly: `${money(p.monthly_min)}–${money(p.monthly_max)}/mo`,
    };
  }
  const setup = p.setup_waived_with_website ? `${money(p.setup)} (waived w/ site)` : money(p.setup);
  return { setup, monthly: `${money(p.monthly)}/mo${p.monthly_label ? ` ${p.monthly_label}` : ""}` };
}

export default function BillingPage() {
  const pricing = loadPricing();
  const products = Object.entries(pricing.products);

  // A real generated contract for the entry product, with clearly-labeled SAMPLE parties. Live
  // contracts fill the agency from agency-facts.yaml and the client from the deal; the generator
  // refuses any blank field or off-ladder price, so this preview IS the validation in action.
  let contractMd: string;
  let contractError: string | null = null;
  try {
    contractMd = generateContract(
      {
        client: { name: "Sample Client LLC", address: "123 Main St, Anytown, TX 75001" },
        agency: { name: "Your Studio", address: "Your business address (from agency-facts.yaml)" },
        productKey: "website",
        setupUsd: 1500,
        monthlyUsd: 99,
      },
      pricing,
    ).markdown;
  } catch (e) {
    contractMd = "";
    contractError = (e as Error).message;
  }

  return (
    <div className="mx-auto max-w-5xl">
      <PageHeader
        title="Pricing"
        description="The offer ladder and the contract generator. Every agreement is validated against this ladder — a mispriced or blank-field contract is impossible to produce."
      />

      <SectionTitle>Offer ladder ({products.length} products)</SectionTitle>
      <div className="mt-2 grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-3">
        {products.map(([key, p]) => {
          const line = priceLine(p);
          return (
            <Card key={key} className="flex flex-col p-4">
              <p className="font-display text-sm font-semibold text-ink">{p.name}</p>
              <div className="mt-2 flex items-baseline gap-2">
                <span className="font-display text-lg font-semibold text-ink">{line.monthly}</span>
              </div>
              <p className="font-display text-[11px] text-faint">setup {line.setup}</p>
              <p className="mt-2 flex-1 text-xs leading-relaxed text-muted">{p.includes}</p>
              {"included_minutes" in p && p.included_minutes && (
                <p className="mt-2 font-display text-[11px] text-data">
                  {p.included_minutes} min/mo included
                  {"overage_per_minute" in p && p.overage_per_minute
                    ? ` · ${money(p.overage_per_minute)}/min overage`
                    : ""}
                </p>
              )}
            </Card>
          );
        })}
      </div>

      <div className="mt-6 grid grid-cols-1 gap-4 lg:grid-cols-2">
        <Card className="p-4">
          <SectionTitle>Contract preview (entry product)</SectionTitle>
          <p className="mt-1 text-xs text-faint">
            Generated by the real validator with sample parties. Blank fields and off-ladder prices are
            rejected before a contract can exist.
          </p>
          {contractError ? (
            <p className="mt-3 text-sm text-danger">contract refused: {contractError}</p>
          ) : (
            <pre className="mt-3 max-h-[420px] overflow-auto whitespace-pre-wrap rounded-lg bg-bg p-3 font-display text-[11px] leading-relaxed text-muted">
              {contractMd}
            </pre>
          )}
        </Card>

        <div className="space-y-4">
          <Card className="p-4">
            <SectionTitle>Contract guardrails</SectionTitle>
            <ul className="mt-2 space-y-1.5 text-sm text-muted">
              <li>Every price is checked against this ladder — no off-ladder agreement can generate.</li>
              <li>No blank required field reaches a client (name, address, fees all validated).</li>
              <li>The rendered output is scanned for unresolved placeholders / NaN before it's returned.</li>
              <li>
                IP is fixed: the client owns their deliverables, the agency owns the platform. Never the
                reverse.
              </li>
            </ul>
          </Card>
          <Card className="p-4">
            <SectionTitle>Guarantees</SectionTitle>
            <div className="mt-2 grid grid-cols-2 gap-3 text-sm">
              <div>
                <p className="font-display text-lg font-semibold text-ink">
                  {pricing.contract.guarantees.uptime_pct}%
                </p>
                <p className="text-xs text-faint">uptime</p>
              </div>
              <div>
                <p className="font-display text-lg font-semibold text-ink">
                  &lt;{pricing.contract.guarantees.speed_to_lead_seconds}s
                </p>
                <p className="text-xs text-faint">speed-to-lead</p>
              </div>
            </div>
            <p className="mt-3 font-display text-[11px] text-faint">
              Backed by service credits, proven from telemetry (measured numbers only).
              {pricing.contract.termination_notice_days}-day termination notice.
            </p>
          </Card>
        </div>
      </div>
    </div>
  );
}
